[[contribute-fixes-and-features]]
= Contribute fixes and features

_JBoss Tools Documentation_ is open source, and we welcome anybody that
wants to participate and contribute!

If you want to fix a bug or make any changes, please log an issue in the
https://issues.jboss.org/browse/JBIDE[JBoss Tools JIRA] describing the
bug or new feature and give it a component type of `documentation`. Then
we highly recommend making the changes on a topic branch named with the
JIRA issue number. For example, this command creates a branch for the
JBIDE-1234 issue:

[source,bash]
----
git checkout -b jbide-1234
----

After you're happy with your changes and a full build (with unit tests)
runs successfully, commit your changes on your topic branch (with good
comments). Then it's time to check for any recent changes that were made
in the official repository:

[source,bash]
----
git checkout master               # switches to the 'master' branch
git pull upstream master          # fetches all 'upstream' changes and merges 
                                  # 'upstream/master' onto your 'master' branch
git checkout jbide-1234           # switches to your topic branch
git rebase master                 # reapplies your changes on top of the latest in master
                                  # (i.e., the latest from master will be the new base for 
                                  # your changes)
----

If the pull grabbed a lot of changes, you should rerun your build with
tests enabled to make sure your changes are still good.

You can then push your topic branch and its changes into your public
fork repository:

[source,bash]
----
git push origin jbide-1234         # pushes your topic branch into your public fork of 
                                   # JBoss Tools Documentation
----

After the push, http://help.github.com/pull-requests/[generate a pull-request]
where we can review the proposed changes, comment on them, discuss them
with you, and if everything is good merge the changes right into the
official repository.
